In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

import ast

In [21]:
# 1. Define the base directory generically
DATA_DIR = Path('C:/Users/iamph/OneDrive/Documents/Datasets/Kaggle_Fitness_Workout_Dataset')

# 2. Safely join the path to the file
file_path = DATA_DIR / 'program_summary.csv'

df = pd.read_csv(file_path)

In [23]:
# 2. Safely join the path to the file
file_path = DATA_DIR / 'programs_detailed_boostcamp_kaggle_CLEAN.csv'

ex = pd.read_csv(file_path)

In [24]:
ex

,title,description,level,goal,equipment,program_length,time_per_workout,week,day,number_of_exercises,exercise_name,sets,reps,intensity,created,last_edit
0,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Bench Press (Barbell),3.0,8.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
1,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Lat Pulldown,3.0,8.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
2,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Military Press (Barbell),3.0,10.0,7.0,2024-07-15 03:29:00,2025-06-27 02:11:00
3,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,T-Bar Row,3.0,12.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
4,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Chest Fly (Cable),3.0,15.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167624,Matt Vena modified,"Modofied version of Matt Vena program, with eq...","{'Beginner', 'Intermediate', 'Advanced', 'Novi...","['Athletics', 'Bodybuilding', 'Powerbuilding',...",Full Gym,12.0,90.0,2.0,1.0,7.0,Wrist Curls,4.0,12.0,10.0,2024-09-07 07:27:00,2025-06-19 06:15:00
167625,Matt Vena modified,"Modofied version of Matt Vena program, with eq...","{'Beginner', 'Intermediate', 'Advanced', 'Novi...","['Athletics', 'Bodybuilding', 'Powerbuilding',...",Full Gym,12.0,90.0,2.0,2.0,8.0,Tempo Bench Press,1.0,12.0,10.0,2024-09-07 07:27:00,2025-06-19 06:15:00
167626,Matt Vena modified,"Modofied version of Matt Vena program, with eq...","{'Beginner', 'Intermediate', 'Advanced', 'Novi...","['Athletics', 'Bodybuilding', 'Powerbuilding',...",Full Gym,12.0,90.0,2.0,2.0,8.0,Deadlift (Barbell),3.0,12.0,10.0,2024-09-07 07:27:00,2025-06-19 06:15:00
167627,Matt Vena modified,"Modofied version of Matt Vena program, with eq...","{'Beginner', 'Intermediate', 'Advanced', 'Novi...","['Athletics', 'Bodybuilding', 'Powerbuilding',...",Full Gym,12.0,90.0,2.0,2.0,8.0,Romanian Deadlift (Barbell),2.0,12.0,10.0,2024-09-07 07:27:00,2025-06-19 06:15:00
167628,Matt Vena modified,"Modofied version of Matt Vena program, with eq...","{'Beginner', 'Intermediate', 'Advanced', 'Novi...","['Athletics', 'Bodybuilding', 'Powerbuilding',...",Full Gym,12.0,90.0,2.0,2.0,8.0,Tricep Rope Push Down (Cable),4.0,10.0,10.0,2024-09-07 07:27:00,2025-06-19 06:15:00

# Did I accidently delete some columns?

In [49]:
# 2. Safely join the path to the file
file_path = DATA_DIR / 'programs_detailed_boostcamp_kaggle.csv'

ex = pd.read_csv(file_path)

In [50]:
def set_mapping(s):
    if s == set(['Intermediate','Beginner']):
        s = set(['Intermediate', 'Novice', 'Beginner'])
    elif s == set(['Beginner', 'Advanced']):
        s = set(['Beginner', 'Novice', 'Intermediate', 'Advanced'])
    elif s == set(['Beginner', 'Intermediate', 'Advanced']):
        s = set(['Beginner', 'Novice', 'Intermediate', 'Advanced'])
    elif s == set(['Novice', 'Advanced']):
        s = set(['Novice', 'Intermediate', 'Advanced'])
    return s

In [51]:
ex['level'] = ex['level'].apply(ast.literal_eval)
ex.level = ex.level.apply(set)
ex.level = ex.level.apply(set_mapping)

In [57]:
titles = list(ex.title.unique())

In [39]:
ex[ex.title == titles[0]] # This was jeff nippard's fundamentals

,title,description,level,goal,equipment,program_length,time_per_workout,week,day,number_of_exercises,exercise_name,sets,reps,intensity,created,last_edit
613,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"['Intermediate', 'Novice']","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Bench Press (Barbell),3.0,8.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
614,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"['Intermediate', 'Novice']","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Lat Pulldown,3.0,8.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
615,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"['Intermediate', 'Novice']","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Military Press (Barbell),3.0,10.0,7.0,2024-07-15 03:29:00,2025-06-27 02:11:00
616,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"['Intermediate', 'Novice']","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,T-Bar Row,3.0,12.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
617,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"['Intermediate', 'Novice']","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Chest Fly (Cable),3.0,15.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,['Beginner'],['Bodybuilding'],Full Gym,8.0,60.0,8.0,4.0,7.0,Romanian Deadlift (Barbell),3.0,10.0,7.0,2024-07-15 03:29:00,2025-06-27 02:11:00
833,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,['Beginner'],['Bodybuilding'],Full Gym,8.0,60.0,8.0,4.0,7.0,Leg Curl,3.0,15.0,9.0,2024-07-15 03:29:00,2025-06-27 02:11:00
834,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,['Beginner'],['Bodybuilding'],Full Gym,8.0,60.0,8.0,4.0,7.0,Standing Calf Raise,3.0,100.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
835,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,['Beginner'],['Bodybuilding'],Full Gym,8.0,60.0,8.0,4.0,7.0,Hanging Leg Raise,3.0,5.0,9.0,2024-07-15 03:29:00,2025-06-27 02:11:00
836,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,['Beginner'],['Bodybuilding'],Full Gym,8.0,60.0,8.0,4.0,7.0,Hip Abductor (Machine),3.0,10.0,9.0,2024-07-15 03:29:00,2025-06-27 02:11:00

In [53]:
ex[ex.title == titles[0]].level.value_counts()

level
{Beginner}                216
{Novice, Intermediate}      8
Name: count, dtype: int64

In [54]:
ex[ex.title == titles[0]].goal.value_counts()

goal
['Bodybuilding']                                           216
['Bodybuilding', 'Powerbuilding', 'Muscle & Sculpting']      8
Name: count, dtype: int64

In [56]:
ex[ex.title == titles[0]].description[613]

'Primary goal is to establish a solid strength base with specifically selected foundational exercises.'

## Another exercise dataset analysis

In [58]:
ex[ex.title == titles[0]]

,title,description,level,goal,equipment,program_length,time_per_workout,week,day,number_of_exercises,exercise_name,sets,reps,intensity,created,last_edit
0,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Knee-to-wall ankle dorsiflexion test,3.0,-180.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
1,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Banded ankle distractions,3.0,-18.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
2,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Slant board calf stretch,3.0,-18.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
3,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Seated Tibialis Raise,3.0,15.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
4,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,90/90 Hip Rotations,3.0,8.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,6.0,1.0,4.0,Overhead Squat w/ Snatch Grip Press at Bottom,3.0,5.0,8.0,2025-03-09 04:11:00,2025-06-23 03:31:00
321,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,6.0,1.0,4.0,Paused Front Squats,3.0,9.0,8.0,2025-03-09 04:11:00,2025-06-23 03:31:00
322,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,6.0,1.0,4.0,Deep Split Jerk Hold,3.0,9.0,8.0,2025-03-09 04:11:00,2025-06-23 03:31:00
323,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,6.0,1.0,4.0,Slow Eccentric Sissy Squats,3.0,14.0,8.0,2025-03-09 04:11:00,2025-06-23 03:31:00
324,Weightlifting Mobility program,This program is designed to help athletes succ...,{},[],Garage Gym,7.0,50.0,7.0,1.0,1.0,Slow Eccentric Sissy Squats,1.0,9.0,8.0,2025-03-09 04:11:00,2025-06-23 03:31:00

In [61]:
ex.title.unique().shape

(2598,)

In [60]:
ex[ex.reps < 0].title.unique().shape

(1247,)

In [62]:
ex[ex.reps < 0]

,title,description,level,goal,equipment,program_length,time_per_workout,week,day,number_of_exercises,exercise_name,sets,reps,intensity,created,last_edit
0,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Knee-to-wall ankle dorsiflexion test,3.0,-180.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
1,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Banded ankle distractions,3.0,-18.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
2,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Slant board calf stretch,3.0,-18.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
8,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Hanging Lat Stretch,3.0,-18.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
13,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Wrist Stretch on Floor,3.0,-18.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604607,Bulk Arc,"The purpose of getting stronger, and becoming ...",{Beginner},['Bodybuilding'],Full Gym,16.0,90.0,16.0,4.0,9.0,Decline Sit Up (Weighted),4.0,-135.0,9.0,2024-12-19 02:11:00,2025-06-19 05:54:00
604632,Full Body Kettlebell and Run Routine,To do a simple kettlebell workout. 1 min rest ...,{Beginner},['Bodybuilding'],Dumbbell Only,1.0,50.0,1.0,5.0,11.0,Kettlebell Swing,1.0,-45.0,9.0,2025-05-17 04:07:00,2025-06-29 04:14:00
604633,Full Body Kettlebell and Run Routine,To do a simple kettlebell workout. 1 min rest ...,"{Advanced, Beginner, Novice, Intermediate}","['Bodybuilding', 'Muscle & Sculpting', 'Bodywe...",Dumbbell Only,1.0,50.0,1.0,5.0,11.0,Goblet Squat,1.0,-135.0,8.0,2025-05-17 04:07:00,2025-06-29 04:14:00
604658,Magic Knight Training Program,Hypetrophy\nModified version of Natural Hyper...,"{Advanced, Beginner, Novice, Intermediate}","['Bodybuilding', 'Muscle & Sculpting', 'Bodywe...",Full Gym,12.0,60.0,1.0,3.0,5.0,Incline Curl (Dumbbell),3.0,-45.0,9.0,2024-09-02 07:24:00,2025-06-18 09:48:00
604659,Magic Knight Training Program,Hypetrophy\nModified version of Natural Hyper...,"{Advanced, Beginner, Novice, Intermediate}","['Bodybuilding', 'Muscle & Sculpting', 'Bodywe...",Full Gym,12.0,60.0,1.0,3.0,5.0,Hanging Leg Raise,3.0,-135.0,8.0,2024-09-02 07:24:00,2025-06-18 09:48:00

In [63]:
ex[ex.reps > 0]

,title,description,level,goal,equipment,program_length,time_per_workout,week,day,number_of_exercises,exercise_name,sets,reps,intensity,created,last_edit
3,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Seated Tibialis Raise,3.0,15.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
4,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,90/90 Hip Rotations,3.0,8.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
5,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Pigeon Stretch with Thoracic Rotation,3.0,6.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
6,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Hip Airplanes,3.0,6.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
7,Weightlifting Mobility program,This program is designed to help athletes succ...,"{Advanced, Beginner, Novice, Intermediate}","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Quadruped T-Spine Rotations,3.0,8.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605028,Matt Vena modified,"Modofied version of Matt Vena program, with eq...",{Intermediate},['Powerbuilding'],Full Gym,12.0,90.0,4.0,1.0,7.0,Squat (Barbell),1.0,12.0,10.0,2024-09-07 07:27:00,2025-06-19 06:15:00
605029,Matt Vena modified,"Modofied version of Matt Vena program, with eq...",{Intermediate},['Powerbuilding'],Full Gym,12.0,90.0,4.0,1.0,7.0,Tempo Squat (Barbell),3.0,12.0,10.0,2024-09-07 07:27:00,2025-06-19 06:15:00
605030,Matt Vena modified,"Modofied version of Matt Vena program, with eq...",{Intermediate},['Powerbuilding'],Full Gym,12.0,90.0,4.0,1.0,7.0,Larsen Press (Barbell),3.0,12.0,10.0,2024-09-07 07:27:00,2025-06-19 06:15:00
605031,Matt Vena modified,"Modofied version of Matt Vena program, with eq...",{Intermediate},['Powerbuilding'],Full Gym,12.0,90.0,4.0,1.0,7.0,Incline Chest Press (Machine),3.0,12.0,10.0,2024-09-07 07:27:00,2025-06-19 06:15:00
605032,Matt Vena modified,"Modofied version of Matt Vena program, with eq...",{Intermediate},['Powerbuilding'],Full Gym,12.0,90.0,4.0,1.0,7.0,Hammer Curl,4.0,12.0,10.0,2024-09-07 07:27:00,2025-06-19 06:15:00

In [64]:
ex.shape

(605033, 16)

In [ ]:
ex.

# Let's observe the progression of workout time (see if there's any varying workout times per program)

In [25]:
titles = list(ex.title.unique())

In [27]:
len(titles)

1567

In [37]:
ex[ex.title == titles[0]] #The program level can change week-by-week...

,title,description,level,goal,equipment,program_length,time_per_workout,week,day,number_of_exercises,exercise_name,sets,reps,intensity,created,last_edit
0,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Bench Press (Barbell),3.0,8.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
1,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Lat Pulldown,3.0,8.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
2,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Military Press (Barbell),3.0,10.0,7.0,2024-07-15 03:29:00,2025-06-27 02:11:00
3,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,T-Bar Row,3.0,12.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
4,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Chest Fly (Cable),3.0,15.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00
5,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Alternating Dumbbell Curl,3.0,15.0,9.0,2024-07-15 03:29:00,2025-06-27 02:11:00
6,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,1.0,7.0,Single Arm Tricep Extension (Cable),3.0,8.0,9.0,2024-07-15 03:29:00,2025-06-27 02:11:00
7,"Jeff Nippard’s Fundamentals, Upper&Lower Split...",Primary goal is to establish a solid strength ...,"{'Novice', 'Intermediate'}","['Bodybuilding', 'Powerbuilding', 'Muscle & Sc...",Full Gym,8.0,60.0,1.0,2.0,7.0,Squat (Barbell),3.0,8.0,8.0,2024-07-15 03:29:00,2025-06-27 02:11:00