In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [6]:
# 1. Define the base directory generically
DATA_DIR = Path('C:/Users/iamph/OneDrive/Documents/Datasets/Kaggle_Fitness_Workout_Dataset')

# 2. Safely join the path to the file
file_path_claude = DATA_DIR / 'values_to_predict_2_MANUAL_LABELED.csv'

file_path_mine = DATA_DIR / 'values_to_predict.csv'

dfm = pd.read_csv(file_path_mine, index_col = 'Column1')

dfc = pd.read_csv(file_path_claude, index_col = 'Column1')

In [7]:
dfm

,exercise_name,norm,label,confidence,adjusted_label
Column1,,,,,
679,Cable Forearm Shit,cable forearm shit,Stretching,20.00%,Arms
408,Weight Over Bar (Highland Games),weight over bar,Arms,20.20%,Legs
523,PullAround,pullaround,Back,21.40%,NaN
713,Weight Over Bar,weight over bar,Back,21.60%,Legs
880,Dynamic Warm-up,dynamic warm up,Shoulders/Neck,22.40%,Cardio/Plyos
...,...,...,...,...,...
1813,Row,row,Back,97.40%,NaN
1736,400m Row,400m row,Back,97.40%,NaN
409,Belt Squat,belt squat,Legs,97.50%,NaN
134,SSB Squat,ssb squat,Legs,98.00%,NaN
1776,Squat,squat,Legs,98.00%,NaN

In [11]:
dfc.rename(columns = {'label':'claude_label'}, inplace = True)

In [12]:
dfm['claude_label'] = dfc.claude_label

In [13]:
dfm

,exercise_name,norm,label,confidence,adjusted_label,claude_label
Column1,,,,,,
679,Cable Forearm Shit,cable forearm shit,Stretching,20.00%,Arms,Arms
408,Weight Over Bar (Highland Games),weight over bar,Arms,20.20%,Legs,Cardio/Plyometrics
523,PullAround,pullaround,Back,21.40%,NaN,Back
713,Weight Over Bar,weight over bar,Back,21.60%,Legs,Cardio/Plyometrics
880,Dynamic Warm-up,dynamic warm up,Shoulders/Neck,22.40%,Cardio/Plyos,Stretching
...,...,...,...,...,...,...
1813,Row,row,Back,97.40%,NaN,NaN
1736,400m Row,400m row,Back,97.40%,NaN,NaN
409,Belt Squat,belt squat,Legs,97.50%,NaN,NaN
134,SSB Squat,ssb squat,Legs,98.00%,NaN,NaN
1776,Squat,squat,Legs,98.00%,NaN,NaN

In [18]:
pd.isnull(dfm.loc[679,'adjusted_label'])

False

In [17]:
pd.isnull(dfm.loc[1776,'adjusted_label'])

True

In [19]:
for idx in dfm.index:
    if pd.isnull(dfm.loc[idx, 'adjusted_label']):
        dfm.loc[idx,'new_label'] = dfm.loc[idx,'label']
    else:
        dfm.loc[idx,'new_label'] = dfm.loc[idx, 'adjusted_label']

In [20]:
dfm

,exercise_name,norm,label,confidence,adjusted_label,claude_label,new_label
Column1,,,,,,,
679,Cable Forearm Shit,cable forearm shit,Stretching,20.00%,Arms,Arms,Arms
408,Weight Over Bar (Highland Games),weight over bar,Arms,20.20%,Legs,Cardio/Plyometrics,Legs
523,PullAround,pullaround,Back,21.40%,NaN,Back,Back
713,Weight Over Bar,weight over bar,Back,21.60%,Legs,Cardio/Plyometrics,Legs
880,Dynamic Warm-up,dynamic warm up,Shoulders/Neck,22.40%,Cardio/Plyos,Stretching,Cardio/Plyos
...,...,...,...,...,...,...,...
1813,Row,row,Back,97.40%,NaN,NaN,Back
1736,400m Row,400m row,Back,97.40%,NaN,NaN,Back
409,Belt Squat,belt squat,Legs,97.50%,NaN,NaN,Legs
134,SSB Squat,ssb squat,Legs,98.00%,NaN,NaN,Legs
1776,Squat,squat,Legs,98.00%,NaN,NaN,Legs

In [22]:
dfm[dfm.claude_label == dfm.new_label]

,exercise_name,norm,label,confidence,adjusted_label,claude_label,new_label
Column1,,,,,,,
679,Cable Forearm Shit,cable forearm shit,Stretching,20.00%,Arms,Arms,Arms
523,PullAround,pullaround,Back,21.40%,NaN,Back,Back
776,Kneeling Landmine Pushes,kneeling landmine pushes,Back,23.70%,Shoulders/Neck,Shoulders/Neck,Shoulders/Neck
1439,Long rope standing overhead ext,long rope standing overhead ext,Shoulders/Neck,24.70%,Arms,Arms,Arms
1414,Flex - Forearms (Placeholder),flex forearms,Stretching,25.10%,Arms,Arms,Arms
...,...,...,...,...,...,...,...
1521,Leg Pres (Low Pad),leg pres,Legs,59.30%,NaN,Legs,Legs
53,Skull Crusher,skull crusher,Arms,59.60%,NaN,Arms,Arms
1427,Rest Pause - Quad Isolation (Placeholder),rest pause quad isolation,Legs,59.80%,NaN,Legs,Legs
430,Arms-Extended 45° Hyperextension,arms extended 45 hyperextension,Back,59.80%,NaN,Back,Back
805,Seated French Press (Dumbbell),seated french press,Arms,59.80%,NaN,Arms,Arms

In [27]:
dfm2 = dfm.copy(deep = True)

In [28]:
dfm2.shape

(1531, 7)

In [30]:
dfm2['confidence'] = dfm2['confidence'].str.rstrip('%').astype('float')

In [31]:
dfm2.head()

,exercise_name,norm,label,confidence,adjusted_label,claude_label,new_label
Column1,,,,,,,
679,Cable Forearm Shit,cable forearm shit,Stretching,20.0,Arms,Arms,Arms
408,Weight Over Bar (Highland Games),weight over bar,Arms,20.2,Legs,Cardio/Plyometrics,Legs
523,PullAround,pullaround,Back,21.4,NaN,Back,Back
713,Weight Over Bar,weight over bar,Back,21.6,Legs,Cardio/Plyometrics,Legs
880,Dynamic Warm-up,dynamic warm up,Shoulders/Neck,22.4,Cardio/Plyos,Stretching,Cardio/Plyos

In [32]:
dfm2[dfm2.confidence > 60]

,exercise_name,norm,label,confidence,adjusted_label,claude_label,new_label
Column1,,,,,,,
1193,Barbell Hyperextension,barbell hyperextension,Back,60.1,NaN,NaN,Back
491,Landmine Press,landmine press,Shoulders/Neck,60.2,NaN,NaN,Shoulders/Neck
494,Banded External Rotation,banded external rotation,Shoulders/Neck,60.3,NaN,NaN,Shoulders/Neck
1083,Supinated Grip Chin-ups,supinated grip chin ups,Back,60.3,NaN,NaN,Back
172,Turkish Get Up,turkish get up,Legs,60.3,NaN,NaN,Legs
...,...,...,...,...,...,...,...
1813,Row,row,Back,97.4,NaN,NaN,Back
1736,400m Row,400m row,Back,97.4,NaN,NaN,Back
409,Belt Squat,belt squat,Legs,97.5,NaN,NaN,Legs
134,SSB Squat,ssb squat,Legs,98.0,NaN,NaN,Legs
1776,Squat,squat,Legs,98.0,NaN,NaN,Legs

In [33]:
dfm2.drop(dfm2[dfm2.confidence > 60].index, inplace = True)

In [34]:
dfm2.shape

(532, 7)

In [35]:
dfm2[dfm2.new_label == dfm2.claude_label]

,exercise_name,norm,label,confidence,adjusted_label,claude_label,new_label
Column1,,,,,,,
679,Cable Forearm Shit,cable forearm shit,Stretching,20.0,Arms,Arms,Arms
523,PullAround,pullaround,Back,21.4,NaN,Back,Back
776,Kneeling Landmine Pushes,kneeling landmine pushes,Back,23.7,Shoulders/Neck,Shoulders/Neck,Shoulders/Neck
1439,Long rope standing overhead ext,long rope standing overhead ext,Shoulders/Neck,24.7,Arms,Arms,Arms
1414,Flex - Forearms (Placeholder),flex forearms,Stretching,25.1,Arms,Arms,Arms
...,...,...,...,...,...,...,...
1521,Leg Pres (Low Pad),leg pres,Legs,59.3,NaN,Legs,Legs
53,Skull Crusher,skull crusher,Arms,59.6,NaN,Arms,Arms
1427,Rest Pause - Quad Isolation (Placeholder),rest pause quad isolation,Legs,59.8,NaN,Legs,Legs
430,Arms-Extended 45° Hyperextension,arms extended 45 hyperextension,Back,59.8,NaN,Back,Back
805,Seated French Press (Dumbbell),seated french press,Arms,59.8,NaN,Arms,Arms

In [36]:
dfm2.

,exercise_name,norm,label,confidence,adjusted_label,claude_label,new_label
Column1,,,,,,,
408,Weight Over Bar (Highland Games),weight over bar,Arms,20.2,Legs,Cardio/Plyometrics,Legs
713,Weight Over Bar,weight over bar,Back,21.6,Legs,Cardio/Plyometrics,Legs
880,Dynamic Warm-up,dynamic warm up,Shoulders/Neck,22.4,Cardio/Plyos,Stretching,Cardio/Plyos
1504,Cycling Cardio,cycling cardio,Cardio/Plyos,23.7,NaN,Cardio/Plyometrics,Cardio/Plyos
1280,Dumbbell Swings,dumbbell swings,Arms,24.0,Legs,Cardio/Plyometrics,Legs
...,...,...,...,...,...,...,...
1763,Smith Good Morning,smith good morning,Legs,59.5,Back,Legs,Back
910,Standing wall angel,standing wall angel,Shoulders/Neck,59.5,Back,Shoulders/Neck,Back
590,Ruck March,ruck march,Legs,59.8,Abs/Core,Cardio/Plyometrics,Abs/Core
433,Reverse Flye (Cable),reverse flye,Shoulders/Neck,59.9,Back,Shoulders/Neck,Back
1785,Cable Reverse Flye,cable reverse flye,Shoulders/Neck,60.0,Back,Shoulders/Neck,Back

In [42]:
dfm2['new_label'] = dfm2['new_label'].replace({'Cardio/Plyos':'Cardio/Plyometrics'})

In [43]:
dfm2[dfm2.new_label == dfm2.claude_label]

,exercise_name,norm,label,confidence,adjusted_label,claude_label,new_label
Column1,,,,,,,
679,Cable Forearm Shit,cable forearm shit,Stretching,20.0,Arms,Arms,Arms
523,PullAround,pullaround,Back,21.4,NaN,Back,Back
776,Kneeling Landmine Pushes,kneeling landmine pushes,Back,23.7,Shoulders/Neck,Shoulders/Neck,Shoulders/Neck
1504,Cycling Cardio,cycling cardio,Cardio/Plyos,23.7,NaN,Cardio/Plyometrics,Cardio/Plyometrics
1188,Ladder Drills,ladder drills,Cardio/Plyos,24.1,NaN,Cardio/Plyometrics,Cardio/Plyometrics
...,...,...,...,...,...,...,...
1521,Leg Pres (Low Pad),leg pres,Legs,59.3,NaN,Legs,Legs
53,Skull Crusher,skull crusher,Arms,59.6,NaN,Arms,Arms
1427,Rest Pause - Quad Isolation (Placeholder),rest pause quad isolation,Legs,59.8,NaN,Legs,Legs
430,Arms-Extended 45° Hyperextension,arms extended 45 hyperextension,Back,59.8,NaN,Back,Back
805,Seated French Press (Dumbbell),seated french press,Arms,59.8,NaN,Arms,Arms

In [45]:
dfm2[dfm2.new_label != dfm2.claude_label].to_csv('differing_values.csv')

In [46]:
dfm2[dfm2.new_label != dfm2.claude_label].shape

(148, 7)

In [47]:
dfm.to_csv('exercises_labelled.csv')