In [2]:
import re
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import classification_report

In [5]:
from pathlib import Path

# Load and clean the data (norm)

In [3]:
def norm(s):
    s = str(s).lower()
    s = re.sub(r'\(.*?\)', '', s)          # strip equipment notes in parens
    s = re.sub(r'[^a-z0-9 ]', ' ', s)
    return re.sub(r'\s+', ' ', s).strip()

In [6]:
# 1. Define the base directory generically
DATA_DIR = Path('C:/Users/iamph/OneDrive/Documents/Datasets/Kaggle_Fitness_Workout_Dataset')

In [8]:
labeled = pd.read_csv(DATA_DIR / 'exercises_dataset_CLEAN.csv')
labeled['norm'] = labeled['exercise'].apply(norm)

prog = pd.read_csv(DATA_DIR / 'programs_detailed_boostcamp_kaggle_CLEAN2.csv')
unique_names = pd.DataFrame({'exercise_name': prog['exercise_name'].unique()})
unique_names['norm'] = unique_names['exercise_name'].apply(norm)

In [11]:
prog.shape

(261897, 16)

In [12]:
prog['exercise_name'].unique()

<StringArray>
[                 'Squat (Barbell)',           'Leg Press (45 Degrees)',
                    'Leg Extension',          'Preacher Curl (Barbell)',
          'Bent Over Row (Barbell)',               'Single Arm Iso Row',
             'Pull-Up (Bodyweight)', 'V-Handle Tricep Pushdown (Cable)',
            'Bench Press (Barbell)',    'Incline Bench Press (Barbell)',
 ...
    'Bottom-Half Seated Cable Flye',                       'T Bar Rows',
    'Seated Barbell Shoulder Press',         'Lat Pulldown Netural TMJ',
            'Kneeling Lat Pulldown',         'Single Arm Rear Delt Fly',
                'Sandbag Box Squat',            'Sandbag Bent-Over Row',
              'Sandbag Floor Press',               'Inverted Face Pull']
Length: 1826, dtype: str

In [9]:
labeled

,exercise,label,norm
0,3/4 sit-up,Abs/Core,3 4 sit up
1,45° side bend,Abs/Core,45 side bend
2,air bike,Abs/Core,air bike
3,all fours squad stretch,Legs,all fours squad stretch
4,alternate heel touchers,Abs/Core,alternate heel touchers
...,...,...,...
4237,EZ-bar skullcrusher-,Arms,ez bar skullcrusher
4238,Lying Close-Grip Barbell Triceps Press To Chin,Arms,lying close grip barbell triceps press to chin
4239,EZ-Bar Skullcrusher - Gethin Variation,Arms,ez bar skullcrusher gethin variation
4240,TBS Skullcrusher,Arms,tbs skullcrusher
4241,30 Arms EZ-Bar Skullcrusher,Arms,30 arms ez bar skullcrusher

In [10]:
unique_names

                 exercise_name                      norm
0              Squat (Barbell)                     squat
1       Leg Press (45 Degrees)                 leg press
2                Leg Extension             leg extension
3      Preacher Curl (Barbell)             preacher curl
4      Bent Over Row (Barbell)             bent over row
...                        ...                       ...
1821  Single Arm Rear Delt Fly  single arm rear delt fly
1822         Sandbag Box Squat         sandbag box squat
1823     Sandbag Bent-Over Row     sandbag bent over row
1824       Sandbag Floor Press       sandbag floor press
1825        Inverted Face Pull        inverted face pull

[1826 rows x 2 columns]

# Layer 1: exact-match bootstrap

In [13]:
# Layer 1: exact-match bootstrap
lookup = labeled.drop_duplicates('norm').set_index('norm')['label']

In [14]:
lookup

norm
3 4 sit up                                        Abs/Core
45 side bend                                      Abs/Core
air bike                                          Abs/Core
all fours squad stretch                               Legs
alternate heel touchers                           Abs/Core
                                                    ...
ez bar skullcrusher                                   Arms
lying close grip barbell triceps press to chin        Arms
ez bar skullcrusher gethin variation                  Arms
tbs skullcrusher                                      Arms
30 arms ez bar skullcrusher                           Arms
Name: label, Length: 4001, dtype: str

In [15]:
unique_names['label'] = unique_names['norm'].map(lookup)
to_predict = unique_names[unique_names['label'].isna()].copy()
print(f"{unique_names['label'].notna().sum()} matched directly, {len(to_predict)} need prediction")

295 matched directly, 1531 need prediction

In [16]:
unique_names

                 exercise_name                      norm label
0              Squat (Barbell)                     squat   NaN
1       Leg Press (45 Degrees)                 leg press  Legs
2                Leg Extension             leg extension  Legs
3      Preacher Curl (Barbell)             preacher curl  Arms
4      Bent Over Row (Barbell)             bent over row   NaN
...                        ...                       ...   ...
1821  Single Arm Rear Delt Fly  single arm rear delt fly   NaN
1822         Sandbag Box Squat         sandbag box squat   NaN
1823     Sandbag Bent-Over Row     sandbag bent over row   NaN
1824       Sandbag Floor Press       sandbag floor press   NaN
1825        Inverted Face Pull        inverted face pull   NaN

[1826 rows x 3 columns]

# Layer 2: Train classifier on labeled set

In [17]:
vectorizer = FeatureUnion([
    ("word", TfidfVectorizer(ngram_range=(1,2), min_df=1, stop_words="english")),
    ("char", TfidfVectorizer(analyzer="char_wb", ngram_range=(3,5), min_df=1)),
])
pipe = Pipeline([("feats", vectorizer), ("clf", LinearSVC(class_weight="balanced", max_iter=5000))])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(pipe, labeled['exercise'], labeled['label'], cv=cv, scoring='f1_macro', n_jobs=-1)
print("CV macro-F1:", scores.mean(), scores.std())

pipe.fit(labeled['exercise'], labeled['label'])
to_predict['label'] = pipe.predict(to_predict['exercise_name'])

CV macro-F1: 0.7400362459617755 0.02123212270243666

In [18]:
scores

array([0.7663953 , 0.70665323, 0.7255511 , 0.7521416 , 0.74944   ])

## Confidence for manual-review triage

In [19]:
# confidence for manual-review triage
margins = pipe.decision_function(to_predict['exercise_name'])
to_predict['confidence'] = margins.max(axis=1) - sorted(margins, key=lambda r: -r[0])[0][0] if False else None

In [24]:
# simpler: margin between top-2 classes
import numpy as np
sorted_margins = np.sort(margins, axis=1)
to_predict['confidence'] = sorted_margins[:, -1] - sorted_margins[:, -2]
  # review these first

,exercise_name,norm,label,confidence
716,Competition (Placeholder),competition,Abs/Core,0.001476
469,Deadlift (Deficit),deadlift,Legs,0.002527
626,Single Leg / Core Accessories,single leg core accessories,Abs/Core,0.002770
985,Sled Drive,sled drive,Legs,0.003811
1210,Loop band Exercise,loop band exercise,Back,0.004218
1816,Bottom-Half Seated Cable Flye,bottom half seated cable flye,Shoulders/Neck,0.004220
343,Pin Press Bench (Barbell),pin press bench,Chest,0.005322
1460,Backward Sled,backward sled,Shoulders/Neck,0.005470
1372,Resisted Rotations,resisted rotations,Abs/Core,0.005554
1040,Loading,loading,Back,0.006435
788,Any Sports,any sports,Legs,0.007037
1453,Reverse Cable Fly,reverse cable fly,Shoulders/Neck,0.007540
1387,Bear Craw Isometric Hold,bear craw isometric hold,Abs/Core,0.010171
1409,Rest Pause - Horizontal Pull (Placeholder),rest pause horizontal pull,Back,0.012793
1676,RDLs,rdls,Back,0.012856
697,Isometric Barbrll hold,isometric barbrll hold,Abs/Core,0.012936
1742,Deadbugs,deadbugs,Abs/Core,0.013685
1624,Lat Press Down,lat press down,Back,0.014212
40,Reverse Pec Deck,reverse pec deck,Legs,0.014254
1111,Incline dumbell skiers,incline dumbell skiers,Chest,0.014424
737,Suite Case Weight Transfer (Abs),suite case weight transfer,Abs/Core,0.015322
1276,Single-Leg Stand,single leg stand,Shoulders/Neck,0.016787
1495,Sandbag To Shoulder,sandbag to shoulder,Stretching,0.016955
608,Neck Extension (Banded Or Plate),neck extension,Arms,0.018006
1755,Push Up Pyramid,push up pyramid,Stretching,0.018191
497,Cobra Pushups,cobra pushups,Chest,0.019787
1362,Leaning Overhead Extension,leaning overhead extension,Arms,0.020003
1257,Reverse Grip Bench,reverse grip bench,Arms,0.020976
1410,Strength - Vertical Push (Placeholder),strength vertical push,Legs,0.021034
1061,Cable Step Up,cable step up,Chest,0.021409

In [31]:
to_predict.sort_values('confidence').head(30)

,exercise_name,norm,label,confidence
716,Competition (Placeholder),competition,Abs/Core,0.001476
469,Deadlift (Deficit),deadlift,Legs,0.002527
626,Single Leg / Core Accessories,single leg core accessories,Abs/Core,0.002770
985,Sled Drive,sled drive,Legs,0.003811
1210,Loop band Exercise,loop band exercise,Back,0.004218
1816,Bottom-Half Seated Cable Flye,bottom half seated cable flye,Shoulders/Neck,0.004220
343,Pin Press Bench (Barbell),pin press bench,Chest,0.005322
1460,Backward Sled,backward sled,Shoulders/Neck,0.005470
1372,Resisted Rotations,resisted rotations,Abs/Core,0.005554
1040,Loading,loading,Back,0.006435
788,Any Sports,any sports,Legs,0.007037
1453,Reverse Cable Fly,reverse cable fly,Shoulders/Neck,0.007540
1387,Bear Craw Isometric Hold,bear craw isometric hold,Abs/Core,0.010171
1409,Rest Pause - Horizontal Pull (Placeholder),rest pause horizontal pull,Back,0.012793
1676,RDLs,rdls,Back,0.012856
697,Isometric Barbrll hold,isometric barbrll hold,Abs/Core,0.012936
1742,Deadbugs,deadbugs,Abs/Core,0.013685
1624,Lat Press Down,lat press down,Back,0.014212
40,Reverse Pec Deck,reverse pec deck,Legs,0.014254
1111,Incline dumbell skiers,incline dumbell skiers,Chest,0.014424
737,Suite Case Weight Transfer (Abs),suite case weight transfer,Abs/Core,0.015322
1276,Single-Leg Stand,single leg stand,Shoulders/Neck,0.016787
1495,Sandbag To Shoulder,sandbag to shoulder,Stretching,0.016955
608,Neck Extension (Banded Or Plate),neck extension,Arms,0.018006
1755,Push Up Pyramid,push up pyramid,Stretching,0.018191
497,Cobra Pushups,cobra pushups,Chest,0.019787
1362,Leaning Overhead Extension,leaning overhead extension,Arms,0.020003
1257,Reverse Grip Bench,reverse grip bench,Arms,0.020976
1410,Strength - Vertical Push (Placeholder),strength vertical push,Legs,0.021034
1061,Cable Step Up,cable step up,Chest,0.021409

In [28]:
to_predict.sort_values('confidence').tail(30)

,exercise_name,norm,label,confidence
1031,Hammer Squat Lung Calf Raises,hammer squat lung calf raises,Legs,3.379435
0,Squat (Barbell),squat,Legs,3.411159
1332,Customisable Row,customisable row,Back,3.464481
1458,Sumo Squat Belt Squat,sumo squat belt squat,Legs,3.472986
1743,Split Squat,split squat,Legs,3.483531
614,Platz Squat,platz squat,Legs,3.551641
789,Batwing Row,batwing row,Back,3.627135
444,Sumo Box Squat,sumo box squat,Legs,3.635805
627,Kroc Row,kroc row,Back,3.640249
467,Leg Press Calf,leg press calf,Legs,3.662958
1232,Bicep Curl (12-15),bicep curl,Arms,3.669067
633,Meadow Row,meadow row,Back,3.683303
1474,Precor Squat,precor squat,Legs,3.685140
634,Erg Row,erg row,Back,3.879437
409,Belt Squat,belt squat,Legs,3.936195
122,Plank,plank,Abs/Core,4.023663
1690,10km Row,10km row,Back,4.385109
672,100m Row,100m row,Back,4.385109
1361,MTS Row,mts row,Back,4.558293
1776,Squat,squat,Legs,4.739313
134,SSB Squat,ssb squat,Legs,4.739313
1734,300m Row,300m row,Back,4.828526
1736,400m Row,400m row,Back,5.014437
622,1km Row,1km row,Back,5.014437
1732,200m Row,200m row,Back,5.014437
1733,250m Row,250m row,Back,5.014437
670,2km Row,2km row,Back,5.014437
671,500m Row,500m row,Back,5.014437
909,5km row,5km row,Back,5.014437
1813,Row,row,Back,5.014437

## Calibrated probabilities to estimate errors

In [32]:
from sklearn.calibration import CalibratedClassifierCV

calibrated = CalibratedClassifierCV(pipe, cv=5, method='sigmoid')
calibrated.fit(labeled['exercise'], labeled['label'])

probs = calibrated.predict_proba(to_predict['exercise_name'])
to_predict['confidence'] = probs.max(axis=1)
to_predict.sort_values('confidence').head(30)  # review these first

,exercise_name,norm,label,confidence
679,Cable Forearm Shit,cable forearm shit,Stretching,0.200470
408,Weight Over Bar (Highland Games),weight over bar,Arms,0.201660
523,PullAround,pullaround,Back,0.214238
713,Weight Over Bar,weight over bar,Back,0.215565
880,Dynamic Warm-up,dynamic warm up,Shoulders/Neck,0.223600
776,Kneeling Landmine Pushes,kneeling landmine pushes,Back,0.236658
1504,Cycling Cardio,cycling cardio,Cardio/Plyos,0.237466
1280,Dumbbell Swings,dumbbell swings,Arms,0.239759
1188,Ladder Drills,ladder drills,Cardio/Plyos,0.240629
564,Cycling,cycling,Cardio/Plyos,0.243867
715,Heavy Weight For Distance,heavy weight for distance,Chest,0.244450
1439,Long rope standing overhead ext,long rope standing overhead ext,Shoulders/Neck,0.247062
1210,Loop band Exercise,loop band exercise,Back,0.248417
1414,Flex - Forearms (Placeholder),flex forearms,Stretching,0.251021
554,Rest,rest,Cardio/Plyos,0.252001
1648,REST,rest,Cardio/Plyos,0.252001
1111,Incline dumbell skiers,incline dumbell skiers,Chest,0.254435
1607,Cycling Intervals,cycling intervals,Cardio/Plyos,0.255328
1489,Lat Pullaround Cross Body,lat pullaround cross body,Back,0.255736
1373,Banded Baseball Complex,banded baseball complex,Shoulders/Neck,0.258523
1432,90-90s,90 90s,Stretching,0.259608
1039,Facepulls,facepulls,Shoulders/Neck,0.261982
933,Rest Day,rest day,Abs/Core,0.264234
1308,Toe Press,toe press,Chest,0.265023
1660,Thoracic Spine Foam Rolling,thoracic spine foam rolling,Back,0.265031
688,Cable Woodchoppers,cable woodchoppers,Chest,0.265499
1679,Dynamic Warmup,dynamic warmup,Chest,0.266853
1659,Foam Rolling,foam rolling,Abs/Core,0.267547
700,Cable Tib Raises,cable tib raises,Chest,0.269310
1747,Dynamic Mobility,dynamic mobility,Chest,0.270307

In [36]:
to_predict.shape

(1531, 4)

In [40]:
to_predict[to_predict.confidence < 0.7].shape

(722, 4)

In [34]:
to_predict.sort_values('confidence').tail(20)

               exercise_name                    norm label  confidence
1458   Sumo Squat Belt Squat   sumo squat belt squat  Legs    0.963416
88          Squat (Dumbbell)                   squat  Legs    0.966032
1361                 MTS Row                 mts row  Back    0.966436
672                 100m Row                100m row  Back    0.966914
1690                10km Row                10km row  Back    0.966914
512   Dumbbell Spanish Squat  dumbbell spanish squat  Legs    0.968554
614              Platz Squat             platz squat  Legs    0.969968
1474            Precor Squat            precor squat  Legs    0.971497
1734                300m Row                300m row  Back    0.972654
622                  1km Row                 1km row  Back    0.974448
671                 500m Row                500m row  Back    0.974448
1732                200m Row                200m row  Back    0.974448
670                  2km Row                 2km row  Back    0.974448
909                  5km row                 5km row  Back    0.974448
1733                250m Row                250m row  Back    0.974448
1813                     Row                     row  Back    0.974448
1736                400m Row                400m row  Back    0.974448
409               Belt Squat              belt squat  Legs    0.974764
134                SSB Squat               ssb squat  Legs    0.979553
1776                   Squat                   squat  Legs    0.979553

In [38]:
to_predict.sort_values('confidence').to_csv('values_to_predict.csv')

# Load manually labelled data

In [43]:
predicted = pd.read_csv(DATA_DIR  / 'exercises_labelled.csv')

In [44]:
predicted

,Column1,exercise_name,norm,label,confidence,adjusted_label,claude_label,new_label
0,679,Cable Forearm Shit,cable forearm shit,Stretching,20.00%,Arms,Arms,Arms
1,408,Weight Over Bar (Highland Games),weight over bar,Arms,20.20%,Legs,Cardio/Plyometrics,Legs
2,523,PullAround,pullaround,Back,21.40%,NaN,Back,Back
3,713,Weight Over Bar,weight over bar,Back,21.60%,Legs,Cardio/Plyometrics,Legs
4,880,Dynamic Warm-up,dynamic warm up,Shoulders/Neck,22.40%,Cardio/Plyos,Stretching,Cardio/Plyos
...,...,...,...,...,...,...,...,...
1526,1813,Row,row,Back,97.40%,NaN,NaN,Back
1527,1736,400m Row,400m row,Back,97.40%,NaN,NaN,Back
1528,409,Belt Squat,belt squat,Legs,97.50%,NaN,NaN,Legs
1529,134,SSB Squat,ssb squat,Legs,98.00%,NaN,NaN,Legs
1530,1776,Squat,squat,Legs,98.00%,NaN,NaN,Legs

In [45]:
unique_names

                 exercise_name                      norm label
0              Squat (Barbell)                     squat   NaN
1       Leg Press (45 Degrees)                 leg press  Legs
2                Leg Extension             leg extension  Legs
3      Preacher Curl (Barbell)             preacher curl  Arms
4      Bent Over Row (Barbell)             bent over row   NaN
...                        ...                       ...   ...
1821  Single Arm Rear Delt Fly  single arm rear delt fly   NaN
1822         Sandbag Box Squat         sandbag box squat   NaN
1823     Sandbag Bent-Over Row     sandbag bent over row   NaN
1824       Sandbag Floor Press       sandbag floor press   NaN
1825        Inverted Face Pull        inverted face pull   NaN

[1826 rows x 3 columns]

In [46]:
unique_names.isnull().sum()

exercise_name       0
norm                0
label            1531
dtype: int64

In [50]:
unique_names

                 exercise_name                      norm label
0              Squat (Barbell)                     squat   NaN
1       Leg Press (45 Degrees)                 leg press  Legs
2                Leg Extension             leg extension  Legs
3      Preacher Curl (Barbell)             preacher curl  Arms
4      Bent Over Row (Barbell)             bent over row   NaN
...                        ...                       ...   ...
1821  Single Arm Rear Delt Fly  single arm rear delt fly   NaN
1822         Sandbag Box Squat         sandbag box squat   NaN
1823     Sandbag Bent-Over Row     sandbag bent over row   NaN
1824       Sandbag Floor Press       sandbag floor press   NaN
1825        Inverted Face Pull        inverted face pull   NaN

[1826 rows x 3 columns]

In [51]:
for row in predicted.itertuples():
    idx = unique_names[unique_names.norm == row.norm].index
    unique_names.loc[idx,'label'] = row.new_label

In [52]:
unique_names

                 exercise_name                      norm           label
0              Squat (Barbell)                     squat            Legs
1       Leg Press (45 Degrees)                 leg press            Legs
2                Leg Extension             leg extension            Legs
3      Preacher Curl (Barbell)             preacher curl            Arms
4      Bent Over Row (Barbell)             bent over row            Back
...                        ...                       ...             ...
1821  Single Arm Rear Delt Fly  single arm rear delt fly  Shoulders/Neck
1822         Sandbag Box Squat         sandbag box squat            Legs
1823     Sandbag Bent-Over Row     sandbag bent over row            Back
1824       Sandbag Floor Press       sandbag floor press           Chest
1825        Inverted Face Pull        inverted face pull  Shoulders/Neck

[1826 rows x 3 columns]

## Create a dictionary for exercise -> label

In [53]:
exercise_label = dict(zip(unique_names['exercise_name'], unique_names['label']))

In [54]:
exercise_label

{'Squat (Barbell)': 'Legs',
 'Leg Press (45 Degrees)': 'Legs',
 'Leg Extension': 'Legs',
 'Preacher Curl (Barbell)': 'Arms',
 'Bent Over Row (Barbell)': 'Back',
 'Single Arm Iso Row': 'Back',
 'Pull-Up (Bodyweight)': 'Back',
 'V-Handle Tricep Pushdown (Cable)': 'Arms',
 'Bench Press (Barbell)': 'Chest',
 'Incline Bench Press (Barbell)': 'Chest',
 'Pec Fly (Dumbbell)': 'Chest',
 'Deadlift (Barbell)': 'Legs',
 'Front Squat (Barbell)': 'Legs',
 'Bulgarian Split Squat (Dumbbell)': 'Legs',
 'Overhead Press (Barbell)': 'Shoulders/Neck',
 'Lateral Raise (Dumbbell)': 'Shoulders/Neck',
 'Incline Bench Press (Dumbbell)': 'Chest',
 'Barbell Row': 'Back',
 'Lat Pulldown': 'Back',
 'Face Pull': 'Shoulders/Neck',
 'Squat (Low Bar)': 'Legs',
 'Romanian Deadlift (Barbell)': 'Legs',
 'Leg Press': 'Legs',
 'Seated Hamstring Curl': 'Legs',
 'Calf Raise (Machine)': 'Legs',
 'Bicep Curl (Barbell)': 'Arms',
 'Hammer Curl (Cable)': 'Arms',
 'Bench Press (Close Grip)': 'Chest',
 'Overhead Tricep Extension (Cable)': 'Arms',
 'Bicep Curl (Cable)': 'Arms',
 'Chest Supported Row (Machine)': 'Back',
 'Seated Row (Cable)': 'Back',
 'Bench Press (Dumbbell)': 'Chest',
 'Chest Fly (Dumbbell)': 'Chest',
 'Standing Pullover (Cable)': 'Back',
 'Hack Squat': 'Legs',
 'Bicep Curl (Dumbbell)': 'Arms',
 'Skull Crusher (Dumbbell)': 'Arms',
 'Tricep Rope Push Down (Cable)': 'Arms',
 'Shoulder Press (Machine)': 'Shoulders/Neck',
 'Reverse Pec Deck': 'Shoulders/Neck',
 'Hamstring Curl': 'Legs',
 'Hammer Curl': 'Arms',
 'Hip Thrust (Barbell)': 'Legs',
 'Standing Calf Raise': 'Legs',
 'Dip (Bodyweight)': 'Arms',
 'Hanging Leg Raise': 'Abs/Core',
 'Incline Curl (Dumbbell)': 'Arms',
 'Deadlift (Paused)': 'Legs',
 'Bench Press (Paused)': 'Chest',
 'Pendlay Row': 'Back',
 'Shrug (Dumbbell)': 'Back',
 'Bicep Curl (EZ Bar)': 'Arms',
 'Skull Crusher': 'Arms',
 'Tricep Pushdown (Cable)': 'Arms',
 'Bicycle Crunch': 'Abs/Core',
 'Single Arm Row (Dumbbell)': 'Back',
 'Squat (Paused)': 'Legs',
 'Leg Curl': 'Legs',
 'Chin-Up (Bodyweight)': 'Back',
 'Arnold Press': 'Shoulders/Neck',
 'Chest Supported Row (Dumbbell)': 'Back',
 'Concentration Curl': 'Arms',
 'Lying Leg Raise': 'Abs/Core',
 'Lat Pulldown (Single Arm)': 'Back',
 'Pec Deck (Machine)': 'Chest',
 'Shrug (Barbell)': 'Back',
 'Upright Row (Dumbbell)': 'Shoulders/Neck',
 'Deadlift (Block)': 'Legs',
 'Seated Row (Machine)': 'Back',
 'Lying Leg Curl': 'Legs',
 'Leg Extension (Cable)': 'Legs',
 'Cable Crunch': 'Abs/Core',
 'Overhead Press (Machine)': 'Shoulders/Neck',
 'Preacher Curl (Machine)': 'Arms',
 'Chest Fly (Machine)': 'Chest',
 'Seated Calf Raise': 'Legs',
 'Bulgarian Split Squat (Smith Machine)': 'Legs',
 'Lat Pulldown (Med - Neutral Grip)': 'Back',
 'Seated Leg Curl (Cable)': 'Legs',
 'Dip (Weighted)': 'Arms',
 'Calf Raise (Leg Press)': 'Legs',
 'Side Bend (Dumbbell)': 'Abs/Core',
 'Lateral Raise (Cable)': 'Shoulders/Neck',
 'Single Arm Overhead Tricep Extension': 'Arms',
 'Chest Press (Machine)': 'Chest',
 'Abs Crunch (Machine)': 'Abs/Core',
 'VO2 Max Intervals': 'Cardio/Plyos',
 'Squat (Dumbbell)': 'Legs',
 'Seated Shoulder Press (Dumbbell)': 'Shoulders/Neck',
 'Romanian Deadlift (Dumbbell)': 'Legs',
 'Split Squat (Dumbbell)': 'Legs',
 'Walking Lunge': 'Legs',
 'Skull Crusher (Barbell)': 'Arms',
 'Tricep Extension (Cable)': 'Arms',
 'Lat Pulldown (Close Grip)': 'Back',
 'Reverse Bicep Curl (EZ Bar)': 'Arms',
 'Wide Grip Pull-Up': 'Back',
 'Goblet Squat': 'Legs',
 'Reverse Lunge (Barbell)': 'Stretching',
 'Romanian Deadlift (Bottom Pause)': 'Legs',
 'Reverse Lunge (Dumbbell)': 'Stretching',
 'Glute Kickback': 'Legs',
 'Wide Grip Lat Pulldown': 'Back',
 'Push Up': 'Chest',
 'Hanging Knee Raise': 'Abs/Core',
 'Wrist Roller': 'Arms',
 'Stiff Leg Deficit Deadlift': 'Legs',
 'Hip Abduction (Band)': 'Legs',
 'Dumbbell External Rotations': 'Shoulders/Neck',
 'Decline Push Up': 'Chest',
 'Lunge (Dumbbell)': 'Legs',
 'Sissy Squat': 'Legs',
 'Stiff Leg Deadlift (Dumbbell)': 'Legs',
 'Single Leg Calf Raise (Weighted)': 'Legs',
 'Powell Raise': 'Shoulders/Neck',
 'Incline Chest Press (Machine)': 'Chest',
 'Calf Extension Machine': 'Legs',
 'Bicep Curl (Machine)': 'Arms',
 'Tricep Extension (Machine)': 'Arms',
 'Upright Row (Cable)': 'Shoulders/Neck',
 'Seated Military Press (Barbell)': 'Shoulders/Neck',
 'Plank': 'Abs/Core',
 'Side Crunch (Cable)': 'Abs/Core',
 'Stiff Leg Deadlift': 'Legs',
 'Russian Twist': 'Abs/Core',
 'Bench Press (Wide Grip)': 'Chest',
 'Sit Up': 'Abs/Core',
 'Shrug (Trap Bar)': 'Back',
 'Back Extension': 'Back',
 'Upright Row (Barbell)': 'Shoulders/Neck',
 'Dumbbell Row': 'Back',
 'Oblique Crunch': 'Abs/Core',
 'Single Leg Romanian Deadlift': 'Legs',
 'SSB Squat': 'Legs',
 'Ab Roller': 'Abs/Core',
 'Ring Pull Ups': 'Back',
 'Lying Tricep Extension (Barbell)': 'Arms',
 'Front Squat (Paused)': 'Legs',
 'Y Raise': 'Shoulders/Neck',
 'Hip Thrust (Machine)': 'Legs',
 'Hip Abductor (Machine)': 'Legs',
 'Hip Adductor (Machine)': 'Legs',
 'Trap Bar Farmers Walk': 'Legs',
 'Seated Overhead Press (Dumbbell)': 'Shoulders/Neck',
 'Lat Pulldown (Neutral Grip)': 'Back',
 'Ab Wheel': 'Abs/Core',
 'Suitcase Carry': 'Abs/Core',
 'Landmine Oblique Twist': 'Abs/Core',
 'Reverse Hyperextension': 'Legs',
 'Jump Squat': 'Legs',
 'Pull-Up (Weighted)': 'Back',
 'Bent Over Row (Dumbbell)': 'Back',
 'Seated Wide-Grip Row (Cable)': 'Back',
 'cable press around': 'Chest',
 'Walk': 'Legs',
 'A Skip': 'Legs',
 'Inchworm': 'Abs/Core',
 'Wall Sit': 'Legs',
 'Pike Push Up': 'Chest',
 'Lunge (Bodyweight)': 'Legs',
 'Plank with Shoulder Taps': 'Abs/Core',
 'Iron Cross': 'Chest',
 'Bear Crawl': 'Cardio/Plyos',
 'Push Up (Knees)': 'Chest',
 'Skater Hop': 'Legs',
 'Dips Between Chairs': 'Arms',
 'Split Squat (Bodyweight)': 'Legs',
 'Superman': 'Stretching',
 'Leg Pull-In': 'Abs/Core',
 'Arm Circle': 'Stretching',
 'Inchworm Walkout': 'Cardio/Plyos',
 'Turkish Get Up': 'Legs',
 'Push Up (Incline)': 'Chest',
 'Rear Foot Elevated Split Squat': 'Legs',
 'Sumo Squat': 'Legs',
 'Marching Glute Bridge': 'Legs',
 'Cannonball Crunch': 'Abs/Core',
 'Lateral Jump': 'Legs',
 'Calf Raise (Bodyweight)': 'Legs',
 'Good Morning (Bodyweight)': 'Legs',
 'Narrow Push Up': 'Chest',
 'Scapular Push Up': 'Chest',
 'Lateral Bear Crawl': 'Cardio/Plyos',
 'Hip Thrust (Bodyweight)': 'Legs',
 'Hollow Rock': 'Abs/Core',
 'Inch Worm + Push Up': 'Chest',
 'Reverse Plank': 'Abs/Core',
 'Squat (Bodyweight)': 'Legs',
 'Bilateral Snapdown': 'Cardio/Plyos',
 'Row Between Chairs': 'Back',
 'Single Leg Calf Raise': 'Legs',
 'Lateral Lunge': 'Legs',
 'Hip Bridge March': 'Legs',
 'Copenhagen Plank': 'Abs/Core',
 'Lateral Shuffle': 'Legs',
 'Hollow Hold': 'Abs/Core',
 'Bird Dog': 'Abs/Core',
 'Wall Press Dead Bug': 'Abs/Core',
 'Skull Crusher (Bodyweight)': 'Arms',
 'Modified Dragon Fly': 'Abs/Core',
 'Split Squat Jump': 'Legs',
 'Bulgarian Split Squat (Bodyweight)': 'Legs',
 'Seated Cable Crunch': 'Abs/Core',
 'Box Jump': 'Legs',
 'Med Ball Slam': 'Abs/Core',
 'Double Leg Multi-Directional Pogo': 'Cardio/Plyos',
 'Kettlebell Swing': 'Legs',
 'Jump Switch Lunge': 'Legs',
 'Power Clean': 'Legs',
 'Battle Ropes': 'Shoulders/Neck',
 'Power Snatch': 'Legs',
 'Back Extension (Weighted)': 'Back',
 'Step-Up (Weighted)': 'Legs',
 'Standing Shoulder Press (Dumbbell)': 'Shoulders/Neck',
 'Glute Kickback (Cable)': 'Legs',
 'Pull Through (Cable)': 'Legs',
 'Straight Leg Calf Raise': 'Legs',
 'Chin-Up (Weighted)': 'Back',
 'Military Press (Barbell)': 'Shoulders/Neck',
 'Lying Side Lateral Raise': 'Shoulders/Neck',
 'Muscle Up (Weighted)': 'Back',
 'Single Arm High Row (Cable)': 'Back',
 'High Bar Squat (Barbell)': 'Legs',
 'Single Arm Row (Cable)': 'Back',
 'Hammer Curl (Dumbbell)': 'Arms',
 'Tempo Bench Press': 'Chest',
 'Front Raise': 'Shoulders/Neck',
 'Single Leg Press': 'Legs',
 'Sumo Deadlift (Paused)': 'Legs',
 'Underhand Lat Pulldown': 'Back',
 'Easy Curl Bent-Over Row': 'Back',
 'Rear Delt Fly (Machine)': 'Shoulders/Neck',
 'Pullover (Dumbbell)': 'Chest',
 'Trap Bar Deadlift': 'Legs',
 'Reverse Nordic Curl': 'Arms',
 'Lateral Raise (Machine)': 'Shoulders/Neck',
 'Pullover (Machine)': 'Chest',
 'Rolling Tricep Extension (Dumbbell)': 'Arms',
 'One Arm Lateral Raise (Dumbbell)': 'Shoulders/Neck',
 'High Row': 'Back',
 'Tricep Extension (Barbell)': 'Arms',
 'Bayesian Curl': 'Arms',
 'T-Bar Row': 'Back',
 'Split Squat Front Foot Elevated (Smith Machine)': 'Legs',
 'Chest Fly (Cable)': 'Chest',
 'Seated Lateral Raise': 'Shoulders/Neck',
 'Wrist Curls': 'Arms',
 'Preacher Curl (EZ Bar)': 'Arms',
 'Pull-Up (Assisted)': 'Back',
 'Seated Flexion Row': 'Back',
 "Farmer's Walk (Weighted)": 'Arms',
 'Standing Behind Neck Shoulder Press (Barbell)': 'Shoulders/Neck',
 'Decline Sit Up (Weighted)': 'Abs/Core',
 'Chin-Up (Assisted)': 'Back',
 'Katana Extension': 'Arms',
 'Unilateral Cable Rear Delt Fly': 'Shoulders/Neck',
 'Lat Prayer': 'Back',
 'Lu Raise': 'Shoulders/Neck',
 'AD Press (Barbell)': 'Shoulders/Neck',
 'Bench Press (Smith Machine)': 'Chest',
 'Seated Overhead Extension (EZ Bar)': 'Arms',
 'Heels Elevated Bulgarian Split Squat (Barbell)': 'Legs',
 'Seated Flyes (Cables)': 'Shoulders/Neck',
 'Good Morning': 'Legs',
 'Ring Push Up': 'Chest',
 'Single Arm Pushdown (Cable)': 'Arms',
 'Bent-Over Row (Smith Machine)': 'Back',
 'Meadows Curl': 'Arms',
 'Zercher Squat (Barbell)': 'Legs',
 'JM Press (Smith Machine)': 'Arms',
 'Behind-The-Neck Press (Smith Machine)': 'Shoulders/Neck',
 'Bent Over Machine Row': 'Back',
 'Incline Fly': 'Chest',
 'Rear Delt Fly (Cable)': 'Shoulders/Neck',
 'Partial Lateral Raise (Cable)': 'Shoulders/Neck',
 'Overhead Extension (Dumbbell)': 'Arms',
 'Pendulum Squat': 'Legs',
 'Tibialis': 'Legs',
 'Pronation Curl': 'Arms',
 'Ghr Sit Up': 'Abs/Core',
 'Hip Extension': 'Legs',
 'Block Pull (Barbell)': 'Legs',
 'Overhead Press (Dumbbell)': 'Shoulders/Neck',
 'Abs Crunch (Weighted)': 'Abs/Core',
 'Squat (Smith Machine)': 'Legs',
 'Larsen Press (Barbell)': 'Chest',
 'Long Pause Bench Press': 'Chest',
 'Box Squat (Barbell)': 'Legs',
 'Rack Pull (Barbell)': 'Back',
 'Hang Clean': 'Legs',
 'Clean (Barbell)': 'Legs',
 'Rear Delt Row': 'Shoulders/Neck',
 'Dragon Flag': 'Abs/Core',
 'Dragon Fly': 'Chest',
 'Incline Pushdown (Cable)': 'Chest',
 'Sumo Deadlift (Barbell)': 'Legs',
 'B-Stance Romanian Deadlift (Dumbbell)': 'Legs',
 'Incline Fly Press (Dumbbell)': 'Chest',
 'Dip (Assisted)': 'Arms',
 'Decline Bench Press (Barbell)': 'Chest',
 'One Arm Cable Lateral Raise, Lean In, Cable Behind Back': 'Shoulders/Neck',
 'Lateral Pull Down, Mid Twisted Grip': 'Back',
 'Lateral Pullover, Rope': 'Back',
 'Bicep Curl, Cable, Bench Out In Front': 'Arms',
 'Calf Raise Smith Machine': 'Legs',
 'Body Weight Row On Barbell': 'Back',
 'Leg Curl Machine (Not Lying)': 'Legs',
 'Incline Bench Press (Smith Machine)': 'Chest',
 'Seated Dip (Machine)': 'Arms',
 "Leg Raise (Captain's Chair)": 'Abs/Core',
 'Alternating Dumbbell Curl': 'Arms',
 'Overhead Extension (EZ Bar)': 'Arms',
 'Spider Curl': 'Arms',
 'Reverse Wrist Curl (Barbell)': 'Arms',
 'Glute Bridge (Bodyweight)': 'Legs',
 'Side Plank': 'Abs/Core',
 'French Press': 'Arms',
 'Spoto Press': 'Chest',
 'JM Press': 'Arms',
 'Seated Dumbbell Curl': 'Arms',
 'Glute Bridge (Barbell)': 'Legs',
 'Plank (Weighted)': 'Abs/Core',
 'Russian Twist (Dumbbell)': 'Abs/Core',
 'Cable Wood Choppers': 'Abs/Core',
 'Reverse Wrist Curl (Dumbbell)': 'Arms',
 'Floor Press (Dumbbell)': 'Arms',
 'Sumo Deadlift (Dumbbell)': 'Legs',
 'Jumping Jack': 'Legs',
 'Run': 'Cardio/Plyos',
 'Deficit Push Up': 'Chest',
 'Seated Overhead Press (Barbell)': 'Shoulders/Neck',
 'Rear Delt Fly (Dumbbell)': 'Shoulders/Neck',
 'Decline Crunch (Weighted)': 'Abs/Core',
 'Tricep Kickback': 'Arms',
 'Push Up (Weighted)': 'Chest',
 'Abs Crunch (Bodyweight)': 'Abs/Core',
 'Twisting Bench Crunches': 'Abs/Core',
 'Plank With Feet On Bench': 'Abs/Core',
 'Wood Chop': 'Abs/Core',
 'Hyperextension': 'Back',
 'Nordic Curl': 'Arms',
 'Prowler Push': 'Chest',
 'Pin Press Bench (Barbell)': 'Chest',
 'Push Press (Barbell)': 'Legs',
 'Light Jog': 'Cardio/Plyos',
 'Cardio (Zone 2)': 'Cardio/Plyos',
 'Landmine Twist': 'Abs/Core',
 'Pallof Press': 'Abs/Core',
 'Walking Lunge (Dumbbell)': 'Legs',
 'TRX Single Leg Squats': 'Legs',
 'Incline Tricep Extension (Dumbbell)': 'Arms',
 'Walking Lunges w/ Pulse': 'Legs',
 'Sprint': 'Legs',
 'Bounds': 'Cardio/Plyos',
 'Goblet Box Squat': 'Legs',
 'Medicine Ball Chest Pass': 'Chest',
 'Plyometric Push Ups': 'Chest',
 'TRX Row': 'Back',
 'Rotational Landmine Push Press': 'Shoulders/Neck',
 'Lateral Med Ball Throw': 'Abs/Core',
 'Pallof Hold': 'Abs/Core',
 'Half Kneeling Starts': 'Cardio/Plyos',
 'Shuttle Run': 'Cardio/Plyos',
 'T Drll': 'Cardio/Plyos',
 'C Drill': 'Cardio/Plyos',
 'Partner Agility Drill': 'Cardio/Plyos',
 'Standing Hip Flexor March': 'Legs',
 'Banded Hip Abduction': 'Legs',
 'Peterson Step Ups': 'Cardio/Plyos',
 'Single Arm Floor Press': 'Arms',
 'Band Pull Apart': 'Shoulders/Neck',
 '21s (EZ Bar)': 'Arms',
 'Mountain Climber': 'Cardio/Plyos',
 'Dead Bug': 'Abs/Core',
 'Goblet March': 'Legs',
 'Preacher Hammer Curl': 'Arms',
 'Flat Dumbbell Press': 'Chest',
 'Incline Hammer Curl (Dumbbell)': 'Arms',
 'High Incline Press': 'Chest',
 'Close Grip Bench Press (Smith Machine)': 'Chest',
 'Preacher Curl (Dumbbell)': 'Arms',
 'Decline Sit Up (Bodyweight)': 'Abs/Core',
 'Close Grip Larsen Press': 'Chest',
 'Deficit Deadlift (Barbell)': 'Back',
 'Overhead Tricep Extension (Dumbbell)': 'Arms',
 'Front Squat (Dumbbell)': 'Legs',
 'Hip Thrust (Dumbbell)': 'Legs',
 'Pinwheel Curl': 'Arms',
 'Renegade Row': 'Back',
 'Lateral Lunge (Weighted)': 'Legs',
 'Safety Bar Squat': 'Legs',
 'Sand Bag Conditioning': 'Abs/Core',
 'Incline Chest Fly (Dumbbell)': 'Chest',
 'Ring Row (Weighted)': 'Back',
 'Single-Leg Leg Curl': 'Legs',
 'Tricep Extension (Dumbbell)': 'Arms',
 'Pull-Up (Neutral Grip, Bodyweight)': 'Back',
 'Shoulder Press (Plate Loaded)': 'Shoulders/Neck',
 'One Arm Lateral Raise (Cable)': 'Shoulders/Neck',
 'Power Shrug': 'Back',
 'Neck Extension': 'Shoulders/Neck',
 'Neck Curl': 'Arms',
 'Viking Press': 'Shoulders/Neck',
 'Frame Hold': 'Shoulders/Neck',
 'Seated Overhead Pin Press (Barbell)': 'Shoulders/Neck',
 'Glute-Ham Raise': 'Legs',
 'Yoke Walk': 'Legs',
 'Weight Over Bar (Highland Games)': 'Legs',
 'Belt Squat': 'Legs',
 'Deficit Row': 'Back',
 'Bent Leg Raise': 'Abs/Core',
 'Cardio': 'Cardio/Plyos',
 'Machine Ab Crunches': 'Abs/Core',
 'Reverse Fly': 'Shoulders/Neck',
 'Hack Squat (Knee Dominant)': 'Legs',
 'Hack Squat Calf Raise': 'Legs',
 'Behind-The-Back Lateral Raise': 'Shoulders/Neck',
 'Low Incline Press (Dumbbell)': 'Chest',
 'Straight-Bar Overhead Triceps Extension (Cable)': 'Arms',
 'Straight-Bar Triceps Pressdown': 'Arms',
 'Cross-Body Lat Pull-Around': 'Back',
 'Chest-Supported Row (Machine)': 'Back',
 'Lat Prayer (Straight-Bar)': 'Back',
 'Hammer Preacher Curl (Dumbbell)': 'Arms',
 'Lying Face Pull (Rope)': 'Shoulders/Neck',
 'Single Leg Hip Thrust': 'Legs',
 'Machine Crunch': 'Abs/Core',
 'Split Squat (Smith Machine)': 'Legs',
 'Wide Grip Seated Row (Cable)': 'Back',
 'Arms-Extended 45° Hyperextension': 'Back',
 'Lean-Back Lat Pulldown': 'Back',
 'Zottman Curl': 'Arms',
 'Reverse Flye (Cable)': 'Back',
 'Shrug (Cable)': 'Back',
 'Cross-Body Y-Raise (Cable)': 'Shoulders/Neck',
 'Low Incline Flye (Dumbbell)': 'Chest',
 'Crossed Overhead Triceps Extension (Cable)': 'Arms',
 'Lean-Back Seated Hip Abduction (Machine)': 'Legs',
 'Cable Crossover': 'Chest',
 'Inverted Row': 'Back',
 'Single Arm Tricep Extension (Cable)': 'Arms',
 'Wide Grip Chest Supported Row': 'Back',
 'Burpee': 'Cardio/Plyos',
 'Sumo Box Squat': 'Legs',
 'Curtsy Lunge (Dumbbell)': 'Legs',
 'Bulgarian Split Squat (Barbell)': 'Legs',
 'Hip abduction': 'Legs',
 'hip adduction (Cable)': 'Legs',
 'Standing Shoulder Press': 'Shoulders/Neck',
 'Single Arm Rear Delt Fly (Cable)': 'Shoulders/Neck',
 'Around The World': 'Shoulders/Neck',
 'One Arm Overhead Carry with March': 'Shoulders/Neck',
 'Reverse Lunge To Overhead Press': 'Shoulders/Neck',
 'Plank Pass Through': 'Abs/Core',
 'Single Arm Pushdown': 'Arms',
 'High Pull': 'Back',
 'Dumbbell Bench Pullover': 'Chest',
 'Pullover (EZ Bar)': 'Chest',
 'One Arm Bent Over Row': 'Back',
 'Lying Pullover (Cable)': 'Chest',
 'Pistol Squat': 'Legs',
 'Lunge (Barbell)': 'Legs',
 'Glute Bridge (Dumbbell)': 'Legs',
 'Decline Crunch': 'Abs/Core',
 'Reverse Abs Crunch (Bodyweight)': 'Abs/Core',
 'Pull-Up (Neutral Grip, Weighted)': 'Back',
 'Leg Press Calf': 'Legs',
 'Rear Delt Neck Supported': 'Shoulders/Neck',
 'Deadlift (Deficit)': 'Legs',
 'Reaching Situp': 'Abs/Core',
 'Lying Reverse Fly': 'Shoulders/Neck',
 'Shoulder YTWL': 'Stretching',
 'Sled Push': 'Cardio/Plyos',
 'Trapbar High Pull': 'Back',
 'Side Lunge': 'Legs',
 'Glute Med Kickback': 'Legs',
 'Trap Bar Power Shrug': 'Back',
 'Straight Arm Pulldown': 'Back',
 'Seated Military Press (Smith Machine)': 'Shoulders/Neck',
 'Conditioning Circuit': 'Cardio/Plyos',
 'Cardio (LISS)': 'Cardio/Plyos',
 'Split Squat (Barbell)': 'Legs',
 'Cable Rear Delt Fly': 'Shoulders/Neck',
 'Pogo Hop': 'Legs',
 '6" Cone Lateral Hops': 'Legs',
 'Sprint 4 Min Recover 4 Min 4 Time': 'Legs',
 'Landmine Kneeling Press': 'Shoulders/Neck',
 'Front Loaded Squats (Sandbag, Odd Object)': 'Legs',
 'Zone 2ish Cardio For 45 Minutes Or So': 'Cardio/Plyos',
 'Close Chest Dumbbell Press': 'Chest',
 'Landmine Press': 'Shoulders/Neck',
 'Pull-Up (Band)': 'Back',
 'Cable twists': 'Abs/Core',
 'Banded External Rotation': 'Shoulders/Neck',
 'Floor Chest Fly (Dumbbell)': 'Chest',
 'Lying Tricep Extension': 'Arms',
 'Cobra Pushups': 'Chest',
 'Scap Pull Down': 'Shoulders/Neck',
 'Straight Arm Pushdown': 'Back',
 'Barbell Strict Curl': 'Arms',
 'Cross Body Hammer Curl': 'Arms',
 'Cable Stretch Drag Curls': 'Arms',
 'Mentzer Pulldown (Trap Set)': 'Back',
 'Banded Pull Apart': 'Shoulders/Neck',
 'Incline Cable Press': 'Chest',
 'PJR Pullover': 'Arms',
 'Cable Tricep Push Away': 'Arms',
 'Cross Body Tricep Extension': 'Arms',
 'Bench Dips': 'Arms',
 'Dumbbell High Pull': 'Back',
 'Banded Overhead Squat': 'Legs',
 'Dumbbell Spanish Squat': 'Legs',
 'Incline Dumbbell Front Raise': 'Shoulders/Neck',
 'Cable Woodchopper': 'Abs/Core',
 'Tricep Kick Back': 'Arms',
 'Rope Crunches': 'Abs/Core',
 'Decline Chest Press': 'Chest',
 'Triceps Extension (Straight Bar)': 'Arms',
 'Cable Low Row': 'Back',
 'Reverse Wrist Curl (Cable)': 'Arms',
 'Skier': 'Cardio/Plyos',
 'Leg Raise Floor': 'Abs/Core',
 'PullAround': 'Back',
 'High Knee Tucks': 'Cardio/Plyos',
 'High Knee Run': 'Cardio/Plyos',
 'Hurdler Stretch': 'Stretching',
 'Butt Kick Run': 'Cardio/Plyos',
 'Figure Four Stretch': 'Stretching',
 'Straight-Leg March': 'Cardio/Plyos',
 'Reverse Lunge Walk': 'Legs',
 'Lateral Lunge Walk': 'Legs',
 'Hamstring Scoops': 'Stretching',
 'Prisoner Squats': 'Legs',
 'Single Leg Toe Touch': 'Stretching',
 'Low Lateral Shuffle': 'Legs',
 'Explosive Carioca': 'Cardio/Plyos',
 'Heel-to-Toe Walk (No Momentum)': 'Cardio/Plyos',
 'Heel-to-Toe Walk (With Momentum)': 'Cardio/Plyos',
 'Heel Walk': 'Legs',
 'Tip-Toe Walk': 'Legs',
 'Fire Hydrant': 'Legs',
 'Hip Circles': 'Stretching',
 'Monster Walk': 'Legs',
 'Pogo Progession': 'Cardio/Plyos',
 'Squat Jumps': 'Legs',
 'Kelso Shrug': 'Back',
 'Reverse Bicep Curl (Dumbbell)': 'Arms',
 'Fly Press (Dumbbell)': 'Chest',
 'Floor Press (Barbell)': 'Arms',
 'Landmine Row': 'Back',
 'Prowler Pull': 'Back',
 'Single dumbbell overhead press': 'Shoulders/Neck',
 'Triceps Kickback (cable)': 'Arms',
 'Rest': 'Rest',
 "Knee Raise (Captain's Chair)": 'Abs/Core',
 'Agachamento Hack Sentado': 'Legs',
 'Single Leg Deadlift': 'Legs',
 'Kettlebell Halo': 'Shoulders/Neck',
 'Optional Lower Body Accessory 1': 'Legs',
 'Dead Hang': 'Arms',
 'Jog': 'Cardio/Plyos',
 'Cable Forearm Curl': 'Arms',
 'Stretching': 'Stretching',
 'Cycling': 'Cardio/Plyos',
 '200m Sprint': 'Legs',
 'Skull Crushers (Smith Machine)': 'Arms',
 'Jump Rope': 'Cardio/Plyos',
 'Treadmill': 'Cardio/Plyos',
 'Behind-the-Neck Lat Pulldown': 'Back',
 'Wrist Rotations': 'Arms',

# Label the original dataset

In [55]:
prog

,title,description,level,goal,equipment,program_length,time_per_workout,week,day,number_of_exercises,exercise_name,sets,reps,intensity,created,last_edit
0,nSuns_Rebuild by KSI,The purpose of this program is to build streng...,"{'Beginner', 'Advanced', 'Intermediate'}","{'Bodybuilding', 'Powerbuilding'}",Full Gym,7.0,90.0,1.0,1.0,4.0,Squat (Barbell),1.0,15.0,8.0,2025-04-06 03:06:00,2025-06-18 08:29:00
1,nSuns_Rebuild by KSI,The purpose of this program is to build streng...,"{'Beginner', 'Advanced', 'Intermediate'}","{'Bodybuilding', 'Powerbuilding'}",Full Gym,7.0,90.0,1.0,1.0,4.0,Leg Press (45 Degrees),1.0,100.0,9.0,2025-04-06 03:06:00,2025-06-18 08:29:00
2,nSuns_Rebuild by KSI,The purpose of this program is to build streng...,"{'Beginner', 'Advanced', 'Intermediate'}","{'Bodybuilding', 'Powerbuilding'}",Full Gym,7.0,90.0,1.0,1.0,4.0,Leg Extension,4.0,5.0,9.0,2025-04-06 03:06:00,2025-06-18 08:29:00
3,nSuns_Rebuild by KSI,The purpose of this program is to build streng...,"{'Beginner', 'Advanced', 'Intermediate'}","{'Bodybuilding', 'Powerbuilding'}",Full Gym,7.0,90.0,1.0,1.0,4.0,Preacher Curl (Barbell),1.0,10.0,9.0,2025-04-06 03:06:00,2025-06-18 08:29:00
4,nSuns_Rebuild by KSI,The purpose of this program is to build streng...,"{'Beginner', 'Advanced', 'Intermediate'}","{'Bodybuilding', 'Powerbuilding'}",Full Gym,7.0,90.0,1.0,2.0,4.0,Bent Over Row (Barbell),1.0,15.0,9.0,2025-04-06 03:06:00,2025-06-18 08:29:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261892,3 Day Baki Grappler Condensed Conjugate (2),This program is designed for martial artists w...,"{'Advanced', 'Intermediate'}","{'Bodybuilding', 'Muscle & Sculpting', 'Athlet...",Garage Gym,4.0,60.0,4.0,3.0,5.0,Overhead Press (Barbell),3.0,1.0,9.0,2025-06-21 03:42:00,2025-06-30 01:20:00
261893,3 Day Baki Grappler Condensed Conjugate (2),This program is designed for martial artists w...,"{'Advanced', 'Intermediate'}","{'Bodybuilding', 'Muscle & Sculpting', 'Athlet...",Garage Gym,4.0,60.0,4.0,3.0,5.0,Barbell Row,3.0,1.0,9.0,2025-06-21 03:42:00,2025-06-30 01:20:00
261894,3 Day Baki Grappler Condensed Conjugate (2),This program is designed for martial artists w...,"{'Advanced', 'Intermediate'}","{'Bodybuilding', 'Muscle & Sculpting', 'Athlet...",Garage Gym,4.0,60.0,4.0,3.0,5.0,Zercher Squat (Barbell),6.0,10.0,9.0,2025-06-21 03:42:00,2025-06-30 01:20:00
261895,3 Day Baki Grappler Condensed Conjugate (2),This program is designed for martial artists w...,"{'Advanced', 'Intermediate'}","{'Bodybuilding', 'Muscle & Sculpting', 'Athlet...",Garage Gym,4.0,60.0,4.0,3.0,5.0,Upright Row (Barbell),4.0,1.0,9.0,2025-06-21 03:42:00,2025-06-30 01:20:00
261896,3 Day Baki Grappler Condensed Conjugate (2),This program is designed for martial artists w...,"{'Advanced', 'Intermediate'}","{'Bodybuilding', 'Muscle & Sculpting', 'Athlet...",Garage Gym,4.0,60.0,4.0,3.0,5.0,Lat Pulldown,7.0,10.0,9.0,2025-06-21 03:42:00,2025-06-30 01:20:00

In [56]:
prog['exercise_label'] = prog['exercise_name'].map(exercise_label)

In [57]:
prog.to_csv('programs_detailed_boostcamp_kaggle_LABELLED.csv')