In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [8]:
# 1. Define the base directory generically
DATA_DIR = Path('C:/Users/iamph/OneDrive/Documents/Datasets/Kaggle_Fitness_Workout_Dataset')

# 2. Safely join the path to the file
file_path = DATA_DIR / 'list_of_exercises_classified.csv'

df1 = pd.read_csv(file_path)

# 2. Safely join the path to the file
file_path = DATA_DIR / 'megaGymDataset.csv'

df2 = pd.read_csv(file_path)

In [9]:
df1

,name,category,muscle_group,target,instructions,exercise_type
0,3/4 sit-up,waist,hip flexors,abs,{'en': 'Lie flat on your back with your knees ...,NaN
1,45° side bend,waist,obliques,abs,{'en': 'Stand with your feet shoulder-width ap...,NaN
2,air bike,waist,hip flexors,abs,{'en': 'Lie flat on your back with your hands ...,NaN
3,all fours squad stretch,upper legs,hamstrings,quads,{'en': 'Start on all fours with your hands dir...,stretch
4,alternate heel touchers,waist,obliques,abs,{'en': 'Lie flat on your back with your knees ...,NaN
...,...,...,...,...,...,...
1319,wide-grip chest dip on high parallel bars,chest,triceps,pectorals,{'en': 'Position yourself on the parallel bars...,NaN
1320,wind sprints,waist,quadriceps,abs,{'en': 'Find an open space or a track to perfo...,NaN
1321,world greatest stretch,upper legs,glutes,hamstrings,{'en': 'Start in a lunge position with your ri...,stretch
1322,wrist circles,lower arms,hands,forearms,{'en': 'Extend your arms straight out in front...,NaN
1323,wrist rollerer,lower arms,biceps,forearms,{'en': 'Attach a weight to one end of a rope o...,NaN

In [10]:
df2

,Title,Desc,Type,BodyPart,Equipment,Level,Rating,RatingDesc
0,Partner plank band row,The partner plank band row is an abdominal exe...,Strength,Abdominals,Bands,Intermediate,0.0,NaN
1,Banded crunch isometric hold,The banded crunch isometric hold is an exercis...,Strength,Abdominals,Bands,Intermediate,NaN,NaN
2,FYR Banded Plank Jack,The banded plank jack is a variation on the pl...,Strength,Abdominals,Bands,Intermediate,NaN,NaN
3,Banded crunch,The banded crunch is an exercise targeting the...,Strength,Abdominals,Bands,Intermediate,NaN,NaN
4,Crunch,The crunch is a popular core exercise targetin...,Strength,Abdominals,Bands,Intermediate,NaN,NaN
...,...,...,...,...,...,...,...,...
2913,EZ-bar skullcrusher-,The EZ-bar skullcrusher is a popular exercise ...,Strength,Triceps,E-Z Curl Bar,Intermediate,8.1,Average
2914,Lying Close-Grip Barbell Triceps Press To Chin,NaN,Strength,Triceps,E-Z Curl Bar,Beginner,8.1,Average
2915,EZ-Bar Skullcrusher - Gethin Variation,The EZ-bar skullcrusher is a popular exercise ...,Strength,Triceps,E-Z Curl Bar,Intermediate,NaN,NaN
2916,TBS Skullcrusher,The EZ-bar skullcrusher is a popular exercise ...,Strength,Triceps,E-Z Curl Bar,Intermediate,NaN,NaN
2917,30 Arms EZ-Bar Skullcrusher,NaN,Strength,Triceps,E-Z Curl Bar,Intermediate,NaN,NaN

# Mega Gym Dataset

In [11]:
df2.BodyPart.unique()

<StringArray>
[ 'Abdominals',   'Adductors',   'Abductors',      'Biceps',      'Calves',
       'Chest',    'Forearms',      'Glutes',  'Hamstrings',        'Lats',
  'Lower Back', 'Middle Back',       'Traps',        'Neck',  'Quadriceps',
   'Shoulders',     'Triceps']
Length: 17, dtype: str

In [17]:
df2.Type.unique()

<StringArray>
[             'Strength',           'Plyometrics',                'Cardio',
            'Stretching',          'Powerlifting',             'Strongman',
 'Olympic Weightlifting']
Length: 7, dtype: str

In [16]:
cat2_conversion = {'Abdominals': 'Abs/Core', 'Adductors': 'Legs', 'Abductors': 'Legs', 'Biceps': 'Arms', \
'Calves': 'Legs', 'Chest': 'Chest', 'Forearms': 'Arms', 'Glutes': 'Legs', 'Hamstrings': 'Legs', 'Lats': 'Back', \
'Lower Back': 'Back', 'Middle Back': 'Back', 'Traps': 'Back', 'Neck': 'Shoulders/Neck', 'Quadriceps': 'Legs', \
'Shoulders': 'Shoulders/Neck', 'Triceps': 'Arms'}

In [20]:
cat2 = np.array([])
for row in df2.itertuples():
    if row.Type in ['Stretching', 'Cardio']:
        cat2 = np.append(cat2, [row.Type])
    else:
        cat2 = np.append(cat2, [cat2_conversion[row.BodyPart]])

In [22]:
df2['label'] = cat2

In [23]:
df2

,Title,Desc,Type,BodyPart,Equipment,Level,Rating,RatingDesc,label
0,Partner plank band row,The partner plank band row is an abdominal exe...,Strength,Abdominals,Bands,Intermediate,0.0,NaN,Abs/Core
1,Banded crunch isometric hold,The banded crunch isometric hold is an exercis...,Strength,Abdominals,Bands,Intermediate,NaN,NaN,Abs/Core
2,FYR Banded Plank Jack,The banded plank jack is a variation on the pl...,Strength,Abdominals,Bands,Intermediate,NaN,NaN,Abs/Core
3,Banded crunch,The banded crunch is an exercise targeting the...,Strength,Abdominals,Bands,Intermediate,NaN,NaN,Abs/Core
4,Crunch,The crunch is a popular core exercise targetin...,Strength,Abdominals,Bands,Intermediate,NaN,NaN,Abs/Core
...,...,...,...,...,...,...,...,...,...
2913,EZ-bar skullcrusher-,The EZ-bar skullcrusher is a popular exercise ...,Strength,Triceps,E-Z Curl Bar,Intermediate,8.1,Average,Arms
2914,Lying Close-Grip Barbell Triceps Press To Chin,NaN,Strength,Triceps,E-Z Curl Bar,Beginner,8.1,Average,Arms
2915,EZ-Bar Skullcrusher - Gethin Variation,The EZ-bar skullcrusher is a popular exercise ...,Strength,Triceps,E-Z Curl Bar,Intermediate,NaN,NaN,Arms
2916,TBS Skullcrusher,The EZ-bar skullcrusher is a popular exercise ...,Strength,Triceps,E-Z Curl Bar,Intermediate,NaN,NaN,Arms
2917,30 Arms EZ-Bar Skullcrusher,NaN,Strength,Triceps,E-Z Curl Bar,Intermediate,NaN,NaN,Arms

In [29]:
df2_new = df2[['Title', 'label']]

In [32]:
df2_new.rename(columns={'Title':'exercise'},inplace=True)

In [34]:
df2_new

                                            exercise     label
0                             Partner plank band row  Abs/Core
1                       Banded crunch isometric hold  Abs/Core
2                              FYR Banded Plank Jack  Abs/Core
3                                      Banded crunch  Abs/Core
4                                             Crunch  Abs/Core
...                                              ...       ...
2913                            EZ-bar skullcrusher-      Arms
2914  Lying Close-Grip Barbell Triceps Press To Chin      Arms
2915          EZ-Bar Skullcrusher - Gethin Variation      Arms
2916                                TBS Skullcrusher      Arms
2917                     30 Arms EZ-Bar Skullcrusher      Arms

[2918 rows x 2 columns]

# Classified Exercises

In [15]:
df1.category.unique()

<StringArray>
[     'waist', 'upper legs',       'back', 'lower legs',      'chest',
 'upper arms',     'cardio',  'shoulders', 'lower arms',       'neck']
Length: 10, dtype: str

In [18]:
cat1_conversion = {'waist': 'Abs/Core', 'upper legs': 'Legs', 'back': 'Back', 'lower legs': 'Legs', \
'chest': 'Chest', 'upper arms': 'Arms', 'cardio': 'Cardio/Plyos', 'shoulders': 'Shoulders/Neck', \
                   'lower arms':'Arms', 'neck': 'Neck'}

In [24]:
df1.head()

,name,category,muscle_group,target,instructions,exercise_type
0,3/4 sit-up,waist,hip flexors,abs,{'en': 'Lie flat on your back with your knees ...,NaN
1,45° side bend,waist,obliques,abs,{'en': 'Stand with your feet shoulder-width ap...,NaN
2,air bike,waist,hip flexors,abs,{'en': 'Lie flat on your back with your hands ...,NaN
3,all fours squad stretch,upper legs,hamstrings,quads,{'en': 'Start on all fours with your hands dir...,stretch
4,alternate heel touchers,waist,obliques,abs,{'en': 'Lie flat on your back with your knees ...,NaN

In [26]:
df1['label'] = df1['category'].map(cat1_conversion)

In [27]:
df1

,name,category,muscle_group,target,instructions,exercise_type,label
0,3/4 sit-up,waist,hip flexors,abs,{'en': 'Lie flat on your back with your knees ...,NaN,Abs/Core
1,45° side bend,waist,obliques,abs,{'en': 'Stand with your feet shoulder-width ap...,NaN,Abs/Core
2,air bike,waist,hip flexors,abs,{'en': 'Lie flat on your back with your hands ...,NaN,Abs/Core
3,all fours squad stretch,upper legs,hamstrings,quads,{'en': 'Start on all fours with your hands dir...,stretch,Legs
4,alternate heel touchers,waist,obliques,abs,{'en': 'Lie flat on your back with your knees ...,NaN,Abs/Core
...,...,...,...,...,...,...,...
1319,wide-grip chest dip on high parallel bars,chest,triceps,pectorals,{'en': 'Position yourself on the parallel bars...,NaN,Chest
1320,wind sprints,waist,quadriceps,abs,{'en': 'Find an open space or a track to perfo...,NaN,Abs/Core
1321,world greatest stretch,upper legs,glutes,hamstrings,{'en': 'Start in a lunge position with your ri...,stretch,Legs
1322,wrist circles,lower arms,hands,forearms,{'en': 'Extend your arms straight out in front...,NaN,Arms
1323,wrist rollerer,lower arms,biceps,forearms,{'en': 'Attach a weight to one end of a rope o...,NaN,Arms

In [28]:
df1_new = df1[['name','label']]

In [35]:
df1_new.rename(columns={'name':'exercise'},inplace=True)

In [37]:
df1_new

                                       exercise     label
0                                    3/4 sit-up  Abs/Core
1                                 45° side bend  Abs/Core
2                                      air bike  Abs/Core
3                       all fours squad stretch      Legs
4                       alternate heel touchers  Abs/Core
...                                         ...       ...
1319  wide-grip chest dip on high parallel bars     Chest
1320                               wind sprints  Abs/Core
1321                     world greatest stretch      Legs
1322                              wrist circles      Arms
1323                             wrist rollerer      Arms

[1324 rows x 2 columns]

# Combine datasets

In [38]:
df_new = pd.concat([df1_new, df2_new])

In [40]:
df_new.to_csv(DATA_DIR / 'exercises_dataset_CLEAN.csv')